// Package java generates Java code from schemas.
package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/konzy/ehrglot/pkg/schema"
)

const Version = "0.1.0"

// Generator generates Java code from schemas.
type Generator struct{}

// NewGenerator creates a new Java code generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate generates Java classes from schemas.
func (g *Generator) Generate(schemas []schema.Schema, outputDir string) error {
	// Group schemas by namespace
	byNamespace := make(map[string][]schema.Schema)
	for _, s := range schemas {
		byNamespace[s.Namespace] = append(byNamespace[s.Namespace], s)
	}

	for namespace, nsSchemas := range byNamespace {
		// Convert namespace to package path (e.g., fhir_r4 -> fhir/r4)
		packagePath := strings.ReplaceAll(namespace, "_", "/")
		nsDir := filepath.Join(outputDir, packagePath)
		if err := os.MkdirAll(nsDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}

		// Generate each schema file
		for _, s := range nsSchemas {
			filename := s.GetName() + ".java"
			path := filepath.Join(nsDir, filename)
			if err := g.generateClass(s, namespace, path); err != nil {
				return err
			}
		}
	}

	return nil
}

func (g *Generator) generateClass(s schema.Schema, namespace string, path string) error {
	tmpl := `/**
 * {{.Schema.Description}}
 *
 * Generated by ehrglot v` + Version + ` at ` + time.Now().Format(time.RFC3339) + `.
 * DO NOT EDIT.
 */
package {{.Package}};

import java.time.LocalDate;
import java.time.Instant;
import java.util.List;

public class {{.Schema | schemaName}} {
{{range .Schema.Fields}}
    private {{.Type | javaType}} {{.Name | camel}};
{{end}}

    public {{.Schema | schemaName}}() {}
{{range .Schema.Fields}}
    public {{.Type | javaType}} get{{.Name | pascal}}() {
        return this.{{.Name | camel}};
    }

    public void set{{.Name | pascal}}({{.Type | javaType}} {{.Name | camel}}) {
        this.{{.Name | camel}} = {{.Name | camel}};
    }
{{end}}
}
`
	funcMap := template.FuncMap{
		"camel":      toCamelCase,
		"pascal":     toPascalCase,
		"javaType":   toJavaType,
		"schemaName": func(s schema.Schema) string { return s.GetName() },
	}

	tmpl_parsed, err := template.New("").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	// Convert namespace to Java package name
	packageName := strings.ReplaceAll(namespace, "_", ".")

	data := struct {
		Schema  schema.Schema
		Package string
	}{
		Schema:  s,
		Package: packageName,
	}

	return tmpl_parsed.Execute(f, data)
}

// GenerateMappings generates Java mapper functions.
func (g *Generator) GenerateMappings(mappings []schema.SchemaMapping, outputDir string) error {
	// TODO: Implement mapping generation
	return nil
}

func toCamelCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if i == 0 {
			words[i] = strings.ToLower(w)
		} else if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	return strings.Join(words, "")
}

func toPascalCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	return strings.Join(words, "")
}

func toJavaType(yamlType string) string {
	switch yamlType {
	case "string", "code", "id", "uri", "url":
		return "String"
	case "integer", "positiveInt", "unsignedInt":
		return "Integer"
	case "decimal":
		return "Double"
	case "boolean":
		return "Boolean"
	case "date":
		return "LocalDate"
	case "datetime", "instant":
		return "Instant"
	case "base64Binary":
		return "byte[]"
	default:
		if strings.HasPrefix(yamlType, "[]") {
			innerType := strings.TrimPrefix(yamlType, "[]")
			return fmt.Sprintf("List<%s>", toJavaType(innerType))
		}
		return "Object"
	}
}
