// Package scala generates Scala code from schemas.
package scala

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/konzy/ehrglot/pkg/schema"
)

const Version = "0.1.0"

// Generator generates Scala code from schemas.
type Generator struct{}

// NewGenerator creates a new Scala code generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate generates Scala case classes from schemas.
func (g *Generator) Generate(schemas []schema.Schema, outputDir string) error {
	// Group schemas by namespace
	byNamespace := make(map[string][]schema.Schema)
	for _, s := range schemas {
		byNamespace[s.Namespace] = append(byNamespace[s.Namespace], s)
	}

	for namespace, nsSchemas := range byNamespace {
		nsDir := filepath.Join(outputDir, namespace)
		if err := os.MkdirAll(nsDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}

		// Generate package file with all case classes
		path := filepath.Join(nsDir, "types.scala")
		if err := g.generateTypes(namespace, nsSchemas, path); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) generateTypes(namespace string, schemas []schema.Schema, path string) error {
	tmpl := `// Generated by ehrglot v` + Version + ` at ` + time.Now().Format(time.RFC3339) + `.
// DO NOT EDIT.

package {{.Package}}

import java.time.{LocalDate, Instant}

{{range .Schemas}}
/**
 * {{.Description}}
 */
case class {{. | schemaName}}(
{{range $i, $f := .Fields}}{{if $i}},
{{end}}  {{$f.Name | camel}}: {{$f | scalaType}}{{end}}
)
{{end}}
`
	funcMap := template.FuncMap{
		"camel":      toCamelCase,
		"scalaType":  toScalaType,
		"schemaName": func(s schema.Schema) string { return s.GetName() },
	}

	tmpl_parsed, err := template.New("").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	// Convert namespace to Scala package name
	packageName := strings.ReplaceAll(namespace, "_", ".")

	data := struct {
		Package string
		Schemas []schema.Schema
	}{
		Package: packageName,
		Schemas: schemas,
	}

	return tmpl_parsed.Execute(f, data)
}

// GenerateMappings generates Scala mapper functions.
func (g *Generator) GenerateMappings(mappings []schema.SchemaMapping, outputDir string) error {
	return nil
}

func toCamelCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if i == 0 {
			words[i] = strings.ToLower(w)
		} else if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	return strings.Join(words, "")
}

func toScalaType(f schema.Field) string {
	baseType := ""
	switch f.Type {
	case "string", "code", "id", "uri", "url":
		baseType = "String"
	case "integer", "positiveInt", "unsignedInt":
		baseType = "Int"
	case "decimal":
		baseType = "BigDecimal"
	case "boolean":
		baseType = "Boolean"
	case "date":
		baseType = "LocalDate"
	case "datetime", "instant":
		baseType = "Instant"
	case "base64Binary":
		baseType = "Array[Byte]"
	default:
		if strings.HasPrefix(f.Type, "[]") {
			innerType := strings.TrimPrefix(f.Type, "[]")
			inner := toScalaType(schema.Field{Type: innerType, Required: true})
			baseType = fmt.Sprintf("Seq[%s]", inner)
		} else {
			baseType = "Any"
		}
	}

	if !f.Required {
		return fmt.Sprintf("Option[%s]", baseType)
	}
	return baseType
}
