// Package typescript generates TypeScript code from schemas.
package typescript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/konzy/ehrglot/pkg/schema"
)

// Generator generates TypeScript code from schemas.
type Generator struct{}

// NewGenerator creates a new TypeScript code generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate generates TypeScript interfaces from schemas.
func (g *Generator) Generate(schemas []schema.Schema, outputDir string) error {
	// Group schemas by namespace
	byNamespace := make(map[string][]schema.Schema)
	for _, s := range schemas {
		byNamespace[s.Namespace] = append(byNamespace[s.Namespace], s)
	}

	for namespace, nsSchemas := range byNamespace {
		nsDir := filepath.Join(outputDir, namespace)
		if err := os.MkdirAll(nsDir, 0755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}

		// Generate index.ts with all types
		path := filepath.Join(nsDir, "index.ts")
		if err := g.generateTypes(nsSchemas, path); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) generateTypes(schemas []schema.Schema, path string) error {
	tmpl := `// Code generated by ehrglot. DO NOT EDIT.

{{range .}}
/**
 * {{.Description}}
 */
export interface {{.Name}} {
{{range .Fields}}  {{.Name | camel}}{{if not .Required}}?{{end}}: {{.Type | tsType}};{{if .Description}} // {{.Description}}{{end}}
{{end}}}
{{end}}
`
	funcMap := template.FuncMap{
		"camel":  toCamelCase,
		"tsType": toTSType,
	}

	tmpl_parsed, err := template.New("").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	return tmpl_parsed.Execute(f, schemas)
}

// GenerateMappings generates TypeScript mapper functions.
func (g *Generator) GenerateMappings(mappings []schema.SchemaMapping, outputDir string) error {
	// TODO: Implement mapping generation
	return nil
}

func toCamelCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		if i == 0 {
			words[i] = strings.ToLower(w)
		} else if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	return strings.Join(words, "")
}

func toTSType(yamlType string) string {
	switch yamlType {
	case "string", "code", "id", "uri", "url", "date", "datetime", "instant":
		return "string"
	case "integer", "positiveInt", "unsignedInt", "decimal":
		return "number"
	case "boolean":
		return "boolean"
	case "base64Binary":
		return "string"
	default:
		if strings.HasPrefix(yamlType, "[]") {
			innerType := strings.TrimPrefix(yamlType, "[]")
			return fmt.Sprintf("%s[]", toTSType(innerType))
		}
		return "unknown"
	}
}
